name: Overwatch
options:
  bundleIdPrefix: com.overwatch
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    SWIFT_ENABLE_EXPLICIT_MODULES: NO
  configs:
    Debug:
      ONLY_ACTIVE_ARCH: YES

packages:
  GoogleGenerativeAI:
    url: https://github.com/google-gemini/generative-ai-swift.git
    from: "0.5.0"

schemes:
  Overwatch:
    build:
      targets:
        Overwatch: all
        OverwatchTests: [test]
    test:
      targets:
        - OverwatchTests

targets:
  Overwatch:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Models
      - path: Services
      - path: Views
      - path: ViewModels
      - path: Theme
      - path: Utilities
    resources:
      - path: Resources
    dependencies:
      - package: GoogleGenerativeAI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.overwatch.app
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/Overwatch.entitlements
        PRODUCT_NAME: Overwatch
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        ENABLE_TESTABILITY: true
    postBuildScripts:
      - script: |
          ENV_FILE="${SRCROOT}/../.env"
          DEST_DIR="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Resources"
          mkdir -p "$DEST_DIR"
          if [ -f "$ENV_FILE" ]; then
            cp "$ENV_FILE" "$DEST_DIR/env.local"
          fi
        name: "Copy .env to Bundle"
        basedOnDependencyAnalysis: false
    entitlements:
      path: App/Overwatch.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true

  OverwatchTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: OverwatchTests
    dependencies:
      - target: Overwatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.overwatch.app.tests
        PRODUCT_NAME: OverwatchTests
        PRODUCT_MODULE_NAME: OverwatchTests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Overwatch.app/Contents/MacOS/Overwatch
        BUNDLE_LOADER: $(TEST_HOST)
